---
collections:
  # AWS Collections
  - name: amazon.aws
  # ServiceNow Collections
  - name: servicenow.itsm
  # Linux Collections
  - name: ansible.posix
  - name: community.general
  - name: containers.podman
  - name: ansible.utils
  # Windows Collections
  - name: ansible.windows
  - name: community.windows
