---
collections:
  # General Collections
  - name: community.general
  - name: ansible.posix
  # MSSQL Collections
  - name: microsoft.sql
  # - name: microsoft.ad
  - name: community.windows
  - name: ansible.windows
  # Red Hat Collections
  # - name: redhat.rhel_system_roles
  #   version: ">=1.23.0"
