---
collections:
  - name: community.general
  - name: ansible.posix
  - name: amazon.aws
  - name: servicenow.itsm
  - name: community.vmware
  - name: vmware.vmware_rest
  - name: vmware.vmware
  # - name: cloud.vmware_ops
