---
collections:
  - name: community.general
  - name: ansible.posix
  - name: amazon.aws
  - name: servicenow.itsm
  - name: community.vmware
  - name: vmware.vmware_rest
  - name: vmware.vmware
  - type: git
    name: https://github.com/redhat-cop/cloud.vmware_ops.git
